### ISSUE TITLE
Problem with using generic page urls

### ISSUE THREAD

**Issue by RandomlyKnighted** [DavidAnson/check-pages#1]
Anytime I try to pass any urls like the following:

index.html
examples/*.html

I get an error saying invalid URL. However, if I point to a producation website, the module works correctly.

**Comment by DavidAnson** [comment]
It sounds like you're trying to point to content on disk? Via pageUrls: [ "localFile.html" ]? That's not a supported scenario - many of the things check-pages does assume a web server is being used. But not all of them - so I'll look into what it would mean to support this scenario soon and follow up here with more information in a week or so. Thanks!

**Comment by RandomlyKnighted** [comment]
Correct, I'm trying to check for invalid links during development so checking against it on disk as you described would be very beneficial. Thank you for looking into this.

**Comment by DavidAnson** [comment]
I use check-pages during development as well. To make things work, my tests start a web server and point check-pages at its localhost address. I've used both grunt-express-server and gulp-develop-server, but any similar approach should work. What's nice about this is that it's almost always going to be closer to the production scenario than hitting the file system would be.

That said, I played around a bit and have a very rough prototype of check-pages working against the file system. :) I'll experiment more in the next few days.

**Comment by RandomlyKnighted** [comment]
Thanks! When will this be available on the npm website for download?

**Comment by DavidAnson** [comment]
I'll publish the new package this evening. :)

**Comment by RandomlyKnighted** [comment]
Fantastic! I appreciate you adding this feature.

**Comment by DavidAnson** [comment]
Published. Let me know if you have any questions!

**Comment by RandomlyKnighted** [comment]
A couple of quick questions about the new feature. First, in the output if there is a time out the right beside the link does that mean it validated that link successfully? Second, does each local file have to be individiually specified under pageUrls? The reason I ask is because I tried to pass it the value

examples/**/*.html

but it tried to actually go to a file called *.html instead of searching the examples folder and all subfolders and looking at the html files in those folders.

**Comment by DavidAnson** [comment]
Here's some sample output from grunt-check-pages (same core engine, it was easier for me to demo with):

```
D:\T\grunt-check-pages>grunt checkPages:local
Running "checkPages:local" (checkPages) task
>> Page: file:test/fileLinks.html (0ms)
>> Link: file:test/validPage.html (16ms)
>> Link: file:test/dir/relativePage.html (0ms)
>> Link error (ENOENT, open 'D:\T\grunt-check-pages\test\NotFound.txt'): file:test/NotFound.txt (0ms)
Warning: 1 issue. (Set options.summary for a summary.) Use --force to continue.
```

The times at the right of each link show how long it took to fetch that link. (Times are much more meaningful for http: links on the web.) If a page fails, it will be called out as an error (shown above).

Because "*" doesn't work for http: links, pages must be listed individually. That requirement was automatically imposed for file: links as well. It's not strictly necessary there, but the current behavior is consistent and I'm expecting this is a fringe case anyway. :)

**Comment by RandomlyKnighted** [comment]
Alright, what about if there are no times to the right of the link? For example, when I updated my gulpfile with each individual page some of my output looked like this:

```text
Page: file:examples/basic.html (9ms)
Link: file:examples/basic.html#! (0ms)
Visited link: file:bower_components/google-code-prettify/src/prettify.css
Visited link: http://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css
Visited link: http://netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.css
Visited link: file:css/style.css
Visited link: http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js
Visited link: file:bower_components/jquery.hotkeys/jquery.hotkeys.js
Visited link: http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js
Visited link: file:bower_components/google-code-prettify/src/prettify.js
Visited link: file:src/bootstrap-wysiwyg.js
```

I'm assuming that because the basic.html shows 9ms that is supposed to represent how long it to check that entire file sucessfully. Is that correct?

**Comment by DavidAnson** [comment]
When it says "Visited link", it means that link has already been seen (as part of an earlier page) and is not being re-checked to save time/bandwidth. If you scroll up, you should see each of those links have "Link:" and a time when they were first encountered.

The times shown are the times required to completely download the page/link (not to analyze it). These timings are informative and can be used by the `maxResponseTime` option to call out particularly slow pages/servers (though being on a very slow network can skew things) that will contribute to a bad user experience.

BTW: I've made a note to document each of the output messages (ex: "Visited link") in the README so this is more clear.

**Comment by RandomlyKnighted** [comment]
Makes sense.

Just a thought, it might be a good idea to also document about wildcards not being accepted in pageUrls and that each page must be added individually.
