### ISSUE TITLE
Feature request: Support attribute srcset

### ISSUE THREAD

**Issue by bit-seq** [DavidAnson/check-pages#2]
In my opinion [attribute `srcset`](https://responsiveimages.org/) would be great to be supported. I tried to provide a complete pull request introducing `srcset`-checks for elements `img` and `source`, however, I wasn't able to integrate this functionality to your tests. To be specific, tests `checkLinksQueryHashes` and `localContentQueryHashesLinksToIgnore` failed on files containing the new attribute tags.

Package [srcset](/sindresorhus/srcset) already parses the attributes content reliable, which should be a good choice to build upon.

**Comment by DavidAnson** [comment]
This was on my TODO list, but I didn't want to have to deal with parsing all the different types of syntax. I love your idea of using a package for this and will look into it soon. Thank you!
